# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ReXpath.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(938, 604)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 891, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_dicom_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load_dicom_btn.setObjectName("load_dicom_btn")
        self.horizontalLayout.addWidget(self.load_dicom_btn)
        self.select_dir_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.select_dir_btn.setObjectName("select_dir_btn")
        self.horizontalLayout.addWidget(self.select_dir_btn)
        self.process_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.process_btn.setObjectName("process_btn")
        self.horizontalLayout.addWidget(self.process_btn)
        self.dicom_table = QtWidgets.QTableWidget(Dialog)
        self.dicom_table.setGeometry(QtCore.QRect(20, 80, 561, 501))
        self.dicom_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.dicom_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dicom_table.setColumnCount(3)
        self.dicom_table.setObjectName("dicom_table")
        self.dicom_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.dicom_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.dicom_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.dicom_table.setHorizontalHeaderItem(2, item)
        self.selected_tags_list = QtWidgets.QListWidget(Dialog)
        self.selected_tags_list.setGeometry(QtCore.QRect(610, 80, 291, 501))
        self.selected_tags_list.setObjectName("selected_tags_list")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ReX - Breaking through the jungle"))
        self.load_dicom_btn.setToolTip(_translate("Dialog", "Elija un archivo DICOM para seleccionar los tags que se utilizarán como método de ordenación."))
        self.load_dicom_btn.setText(_translate("Dialog", "Cargar archivo DICOM de referencia"))
        self.select_dir_btn.setToolTip(_translate("Dialog", "Seleccione la carpeta que contiene los archivos DICOM. Pueden encontrarse en subcarpetas."))
        self.select_dir_btn.setText(_translate("Dialog", "Seleccionar directorio objetivo"))
        self.process_btn.setToolTip(_translate("Dialog", "Cuando se hayan seleccionado un directorio y uno o más tags, ejecuta la ordenación."))
        self.process_btn.setText(_translate("Dialog", "Ordenar archivos"))
        item = self.dicom_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Tag"))
        item = self.dicom_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.dicom_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Value"))
